### ISSUE TITLE
anydesk is not installed correctly

### ISSUE THREAD

**Issue by ghazaleaghaei** [HolismHolding/Issues#183]
When installing AnyDesk in ubuntu 24.04 , it gives this error,

![Screenshot from 2024-05-07 19-36-43](https://github.com/HolismHolding/Issues/assets/95690607/9030b6af-a427-443e-9462-f719b195c8f3)

and when I open AnyDesk, the close and minimize buttons and the top of the screen don't work anymore

https://github.com/HolismHolding/Issues/assets/95690607/fd00d7d8-91aa-42a9-b151-4471b58d36fd

I searched a lot but did not find any results. Thank you for your help

**Comment by hosseinitabar** [comment]
This is a common occurrence since Ubuntu 24.04 is a new release, and software compatibility isn't fully established yet.
Here's what you can do:
```
sudo apt update
sudo apt install anydesk
sudo apt --fix-broken install
```
I had the same error, but now my Any Desk works correctly

Of course, the mouse clicks on the top right corner of the screen (close, maximize, and minimize buttons) have a problem and are not selected correctly
Temporarily, when using that area, you can use the Win key + Down arrow key to exit the screen from maximize mode and maximize the screen again with the Windows key + Up arrow key.
No problem, errors will be fixed in the future

**Comment by ghazaleaghaei** [comment]
thank you
